Repository P2P-Develop/PeyangSuperbAntiCheat, pull requests merged in 2020-07, with the labels that each got.

#19 Avoid alias conflicts with other plugins
  docs/README-en.md
  docs/README-ja.md
  src/main/resources/plugin.yml
Labels: bug

#20 スピードを調整
  docs/README-en.md
  docs/README-ja.md
  src/main/java/ml/peya/plugins/Detect/NPCTeleport.java
  src/main/resources/config.yml
Labels: bug, discussion, enhancement

#31 Machine learning and version adjustment (Stable Request)
  PeyangSuperbAntiCheat.iml
  pom.xml
  src/main/java/ml/peya/plugins/Commands/CmdPub/Learn.java
  src/main/java/ml/peya/plugins/Commands/CommandPeyangSuperbAntiCheat.java
  src/main/java/ml/peya/plugins/Detect/DetectConnection.java
  src/main/java/ml/peya/plugins/Init.java
  src/main/java/ml/peya/plugins/PeyangSuperbAntiCheat.java
Labels: bug, dependencies, enhancement

#32 Release 0.3 - Stable merge
  .flooignore
  .github/workflows/maven-dev.yml
  .github/workflows/maven-stable.yml
  .gitignore
  PeyangSuperbAntiCheat.iml
  SECURITY-en.md
  SECURITY.md
  Vulnerabilities.md
  docs/README-en.md
  docs/README-ja.md
  install
  pom.xml
  src/main/java/ml/peya/plugins/Commands/CmdPub/Learn.java
  src/main/java/ml/peya/plugins/Commands/CommandPeyangSuperbAntiCheat.java
  src/main/java/ml/peya/plugins/Detect/DetectConnection.java
  src/main/java/ml/peya/plugins/DetectClasses/CheatDetectNowMeta.java
  src/main/java/ml/peya/plugins/DetectClasses/DetectingList.java
  src/main/java/ml/peya/plugins/Enum/DetectType.java
  src/main/java/ml/peya/plugins/Enum/EnumCheatType.java
  src/main/java/ml/peya/plugins/Enum/EnumSeverity.java
  src/main/java/ml/peya/plugins/Init.java
  src/main/java/ml/peya/plugins/Learn/Input.java
  src/main/java/ml/peya/plugins/Learn/LearnMath.java
  src/main/java/ml/peya/plugins/Learn/NeuralNetwork.java
  src/main/java/ml/peya/plugins/Learn/Neuron.java
  src/main/java/ml/peya/plugins/Metrics.java
  src/main/java/ml/peya/plugins/PeyangSuperbAntiCheat.java
  src/main/java/ml/peya/plugins/Utils/StringUtil.java
  src/main/resources/config.yml
Labels: release
